name: CI

on: 
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install NPM
        run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true